### ISSUE TITLE
Does not compile with openresty-1.13.5.1rc0

### ISSUE THREAD

**Issue by anthonyryan** [openresty/lua-resty-upstream-healthcheck#48]
Looked for similar issues on other revs but can't find an exact patch. Any suggestions?
openresty-1.13.5.1rc0
nginx-1.13.5

```
--2017-10-21 17:09:50--  https://github.com/openresty/lua-resty-upstream-healthcheck/tarball/v0.05
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/openresty/lua-resty-upstream-healthcheck/legacy.tar.gz/v0.05 [following]
--2017-10-21 17:09:50--  https://codeload.github.com/openresty/lua-resty-upstream-healthcheck/legacy.tar.gz/v0.05
Resolving codeload.github.com (codeload.github.com)... 192.30.253.121, 192.30.253.120
Connecting to codeload.github.com (codeload.github.com)|192.30.253.121|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘lua-resty-upstream-healthcheck-0.05.tar.gz’
 
0K .......... ..                                          9.72M=0.001s
 
2017-10-21 17:09:50 (9.72 MB/s) - ‘lua-resty-upstream-healthcheck-0.05.tar.gz’ saved [12463]
 
unix2dos: converting file README-win32.txt to DOS format ...
/tmp/nginx-upstream-fair/ngx_http_upstream_fair_module.c: In function ‘ngx_http_upstream_init_fair_rr’:
/tmp/nginx-upstream-fair/ngx_http_upstream_fair_module.c:543:28: error: ‘ngx_http_upstream_srv_conf_t {aka struct ngx_http_upstream_srv_conf_s}’ has no member named ‘default_port’
if (us->port == 0 && us->default_port == 0) {
^
/tmp/nginx-upstream-fair/ngx_http_upstream_fair_module.c:553:51: error: ‘ngx_http_upstream_srv_conf_t {aka struct ngx_http_upstream_srv_conf_s}’ has no member named ‘default_port’
u.port = (in_port_t) (us->port ? us->port : us->default_port);
^
ake[2]: *** [objs/addon/nginx-upstream-fair/ngx_http_upstream_fair_module.o] Error 1
ake[1]: *** [build] Error 2
ake: *** [all] Error 2
```

**Comment by agentzh** [comment]
@anthonyryan It is your own 3rd-party module nginx-upstream-fair which fails to support the 1.13.x nginx core, not a problem of ours.

**Comment by anthonyryan** [comment]
uh okay
